### PR TITLE
Added python 3 compatibility

### PR DESCRIPTION
**Pull request by philip-sterne**
Python 3 compatibility added.  This only required rewriting certain anonymous lambda reductions to `sum` calls, as well as putting parentheses around some `print` calls.

PEP8 compatibility has been improved using the default settings from YAPF.

All tests pass with Python 2 and Python 3.  The travis builds also successfully complete.

### CODE REVIEW

**Comment by ilyakava** [comment]
Hi philip-sterne, thank you for your work! Are you able to separate the formatting commit from the python 3 compatibility commit please?

**Comment by philip-sterne** [comment]
If at all possible I'd rather not (though I appreciate that it makes the
review easier).

The only actual code changes were rewriting the `reduce` lambda functions
to simple sums. I think that there were 3-4 of them. There were also some
print calls which needed parentheses.

Those were literally the only changes.

**Comment by ilyakava** [comment]
Okay. Can you then please fix the 2.7 build (remove the `--use-mirrors`) and add a 3.5 build for Travis CI?

p.s. I mean in a separate commit of course.

**Comment by ilyakava** [comment]
And can you also change the commit message to be something like "Reformatted to PEP8 and etc etc"?

**Comment by philip-sterne** [comment]
Ok - all changes made, and I rebased everything into a single commit.  (The second commit only affected .travis.yml)

**Comment by ilyakava** [comment]
Thank you! Will release soon

**Comment by ilyakava** [comment]
Just [released](https://pypi.python.org/pypi/sumproduct/0.0.7). Thank you @philip-sterne !

**Pull request merged**
